# This is a basic workflow to help you get started with Actions

name: pre-merge

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    branches: ["master"]
    paths-ignore:
      - .github/**

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  api-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: install deps
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install jupyterlab pandas matplotlib sympy

      - name: install py3d
        run: python3 -m pip install -e py3d

      - name: test
        run: python3 test.py -d docs

      - name: commit docs
        run: |
          git config user.email "hh11698@163.com"
          git config user.name "Tumiz"
          git add docs py3d/README.md
          git commit -m "update docs"
          git push
